package com.example.stocktick.ui.insurance

data class InsuranceModel(
        val type : String? = null,
        val name : String? = null,
        val email : String? = null,
        val mobile : String? = null,
        val location : String? = null,
        val manufac_date : String? = null,
        val variant : String? = null,
        val current_insurer : String? = null,
        val puc_expiry : String? = null,
        val policy_expiry : String? = null,
        val businessTitle : String? = null,
        val manufacturer : String? = null,
        val fuel_type : String? = null,
        val model : String? = null,
        val puc : String? = null,
        val current_policy_claim : String? = null,
        val vehicle_number : String? = null,
        val month_12_ownership : String? = null,
        val policyType : String? = null,
        val insurance_for : String? = null,
        val insurer_name : String? = null,
        val insurer_age : String? = null,
        val age : String?= null,
        val medical : String? = null,
        val dob : String? = null,
        val cover_life : String? = null,
        val cover_upto : String? = null,
        val amount : String? = null
)
