package com.example.stocktick.ui.mutual_funds.asset_recorder.fragments.fd.fragments

import android.os.Bundle
import android.view.View
import androidx.fragment.app.Fragment
import androidx.fragment.app.activityViewModels
import androidx.navigation.findNavController
import androidx.navigation.fragment.navArgs
import com.example.stocktick.R
import com.example.stocktick.databinding.FragmentFdDetailsBinding
import com.example.stocktick.ui.mutual_funds.asset_recorder.fragments.fd.FdViewModel
import com.example.stocktick.ui.mutual_funds.asset_recorder.models.domain.FixedDeposit

class FdDetails : Fragment( R.layout.fragment_fd_details) {

   private lateinit var binding: FragmentFdDetailsBinding
   private val viewModel : FdViewModel by activityViewModels()

   private val args: FdDetailsArgs by navArgs()

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        val navController = view.findNavController()
        binding = FragmentFdDetailsBinding.bind(view)
        val details : FixedDeposit? = try {
            viewModel.getElement(
                position = args.position
            )
        } catch (e: IndexOutOfBoundsException){
            null
        }
        if (details == null) navController.navigateUp()

        binding.fabEdit.setOnClickListener{
            val action = FdDetailsDirections.actionFdDetailsToFdDetailsEdit(args.position)
            view.findNavController().navigate(action)
        }

        //autogenerated
        if (details!!.nominee_name.isEmpty()){
            binding.nomineeName.visibility = View.GONE
            binding.nomineeNameLabel.visibility = View.GONE}
        else {
            binding.nomineeName.text = details.nominee_name
        }

        if (details!!.relationship.isEmpty()){
            binding.relationship.visibility = View.GONE
            binding.relationshipLabel.visibility = View.GONE}
        else {
            binding.relationship.text = details.relationship
        }

        if (details!!.bank_name.isEmpty()){
            binding.bankName.visibility = View.GONE
            binding.bankNameLabel.visibility = View.GONE}
        else {
            binding.bankName.text = details.bank_name
        }

        if (details!!.branch_addr.isEmpty()){
            binding.branchAddress.visibility = View.GONE
            binding.branchAddressLabel.visibility = View.GONE}
        else {
            binding.branchAddress.text = details.branch_addr
        }

        if (details!!.deposit_holders_name.isEmpty()){
        binding.depositHoldersName.visibility = View.GONE
        binding.depositHoldersNameLabel.visibility = View.GONE}
        else {
            binding.depositHoldersName.text = details.deposit_holders_name
        }

        if (details!!.amount_invested.isEmpty()){
            binding.amountInvested.visibility = View.GONE
            binding.amountInvestedLabel.visibility = View.GONE}
        else {
            val str = "${details.amount_invested} INR"
            binding.amountInvested.text = str
        }

        if (details!!.investment_date.isEmpty()){
            binding.investmentDate.visibility = View.GONE
            binding.investmentDateLabel.visibility = View.GONE}
        else {
            binding.investmentDate.text = details.investment_date
        }

        if (details!!.investment_duration.isEmpty()){
            binding.investmentDuration.visibility = View.GONE
            binding.investmentDurationLabel.visibility = View.GONE}
        else {
            binding.investmentDuration.text = details.investment_duration
        }

        if (details!!.rate_of_interest.isEmpty()){
            binding.rateOfInterest.visibility = View.GONE
            binding.rateOfInterestLabel.visibility = View.GONE}
        else {
            binding.rateOfInterest.text = details.rate_of_interest
        }

        if (details!!.maturity_date.isEmpty()){
            binding.maturityDate.visibility = View.GONE
            binding.maturityDateLabel.visibility = View.GONE}
        else {
            binding.maturityDate.text = details.maturity_date
        }

        if (details!!.maturity_amount.isEmpty()){
            binding.maturityAmount.visibility = View.GONE
            binding.maturityAmountLabel.visibility = View.GONE}
        else {
            binding.maturityAmount.text = details.maturity_amount
        }

        if (details!!.nominee_name2.isEmpty()){
            binding.nomineeName2.visibility = View.GONE
            binding.nomineeNameLabel2.visibility = View.GONE}
        else {
            binding.nomineeName2.text = details.nominee_name2
        }

        if (details!!.relationship2.isEmpty()){
            binding.relationship2.visibility = View.GONE
            binding.relationshipLabel2.visibility = View.GONE}
        else {
            binding.relationship2.text = details.relationship2
        }

        if (details!!.allocation.isEmpty()){
            binding.allocation.visibility = View.GONE
                    binding.allocationLabel.visibility = View.GONE}
        else {
            binding.allocation.text = details.allocation
        }

        if (details!!.allocation2.isEmpty()){
            binding.allocation2.visibility = View.GONE
            binding.allocationLabel2.visibility = View.GONE}
        else {
            binding.allocation2.text = details.allocation2
        }
    }
}