package com.example.stocktick.ui.mutual_funds.asset_recorder.fragments.pms.fragments

import android.os.Bundle
import android.view.View
import androidx.fragment.app.Fragment
import androidx.fragment.app.activityViewModels
import androidx.navigation.findNavController
import androidx.navigation.fragment.navArgs
import com.example.stocktick.R
import com.example.stocktick.databinding.FragmentPmsDetailsBinding
import com.example.stocktick.ui.mutual_funds.asset_recorder.fragments.pms.PmsViewModel
import com.example.stocktick.ui.mutual_funds.asset_recorder.models.domain.PmsModel

class PmsDetails : Fragment( R.layout.fragment_pms_details) {

    private lateinit var binding: FragmentPmsDetailsBinding
    private val viewModel : PmsViewModel by activityViewModels()

    private val args: PmsDetailsArgs by navArgs()

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        val navController = view.findNavController()
        binding = FragmentPmsDetailsBinding.bind(view)
        val details : PmsModel? = try {
            viewModel.getElement(
                position = args.position
            )
        } catch (e: IndexOutOfBoundsException){
            null
        }
        if (details == null) navController.navigateUp()

        binding.fabEdit.setOnClickListener{
            val action = PmsDetailsDirections.actionPmsDetailsToPmsDetailsEdit(args.position)
            view.findNavController().navigate(action)
        }

        //autogenerated
        if (details!!.amc_name.isEmpty()){
            binding.amcName.visibility = View.GONE
            binding.amcNameLabel.visibility = View.GONE}
        else {
            binding.amcName.text = details.amc_name
        }

        if (details!!.pms_aif_name.isEmpty()){
            binding.pmsAifName.visibility = View.GONE
            binding.pmsAifNameLabel.visibility = View.GONE}
        else {
            binding.pmsAifName.text = details.pms_aif_name
        }

        if (details!!.invested_value.isEmpty()){
            binding.investedValue.visibility = View.GONE
            binding.investedValueLabel.visibility = View.GONE}
        else {
            binding.investedValue.text = details.invested_value
        }

        if (details!!.current_amount.isEmpty()){
            binding.currentAmount.visibility = View.GONE
            binding.currentAmountLabel.visibility = View.GONE}
        else {
            binding.currentAmount.text = details.current_amount
        }

        if (details!!.account_number.isEmpty()){
            binding.accountNumber.visibility = View.GONE
            binding.accountNumberLabel.visibility = View.GONE}
        else {
            binding.accountNumber.text = details.account_number
        }

        if (details!!.invested_date.isEmpty()){
            binding.investedDate.visibility = View.GONE
            binding.investedDateLabel.visibility = View.GONE}
        else {
            binding.investedDate.text = details.invested_date
        }

        if (details!!.return_absolute.isEmpty()){
            binding.returnAbsolute.visibility = View.GONE
            binding.returnAbsoluteLabel.visibility = View.GONE}
        else {
            binding.returnAbsolute.text = details.return_absolute
        }

        if (details!!.return_cagr.isEmpty()){
            binding.returnCagr.visibility = View.GONE
            binding.returnCagrLabel.visibility = View.GONE}
        else {
            binding.returnCagr.text = details.return_cagr
        }

        if (details!!.nominee_name.isEmpty()){
            binding.nomineeName.visibility = View.GONE
            binding.nomineeNameLabel.visibility = View.GONE}
        else {
            binding.nomineeName.text = details.nominee_name
        }

        if (details!!.relationship.isEmpty()){
            binding.relationship.visibility = View.GONE
            binding.relationshipLabel.visibility = View.GONE}
        else {
            binding.relationship.text = details.relationship
        }

        if (details!!.allocation_percent.isEmpty()){
            binding.allocationPercent.visibility = View.GONE
            binding.allocationPercentLabel.visibility = View.GONE}
        else {
            binding.allocationPercent.text = details.allocation_percent
        }

        if (details!!.nominee_name2_.isEmpty()){
            binding.nomineeName2.visibility = View.GONE
            binding.nomineeName2Label.visibility = View.GONE}
        else {
            binding.nomineeName2.text = details.nominee_name2_
        }

        if (details!!.relationship2.isEmpty()){
            binding.Relationship2.visibility = View.GONE
            binding.Relationship2Label.visibility = View.GONE}
        else {
            binding.Relationship2.text = details.relationship2
        }

        if (details!!.allocation_percent2.isEmpty()){
            binding.allocationPercent2.visibility = View.GONE
            binding.allocationPercent2Label.visibility = View.GONE}
        else {
            binding.allocationPercent2.text = details.allocation_percent2
        }

    }
}